/// embed.rs — CPU embedding inference via `tract-onnx` (pure Rust, no C deps) + HuggingFace
/// `tokenizers`.
///
/// The public interface is [`Embedder`], which exposes:
///
/// - [`Embedder::load`]        — load a real ONNX model from disk
/// - [`Embedder::stub`]        — deterministic random-unit-vector embedder for testing
/// - [`Embedder::embed_batch`] — embed a slice of strings, returns Vec<Vec<f32>>
/// - [`Embedder::embed_one`]   — convenience wrapper for a single string
/// - [`Embedder::model_sha256`] — sha256 hex of the model file bytes (for DB meta check)
///
/// ## Real model
///
/// [`Embedder::load`] accepts a path to an `.onnx` file.  The tokenizer is expected at
/// `{model_dir}/tokenizer.json`.
///
/// The model takes standard BERT-style inputs and outputs either `sentence_embedding`
/// (pre-pooled) or `last_hidden_state` (mean-pooled by us).  All vectors are L2-normalised.
///
/// ## Stub mode
///
/// [`Embedder::stub`] returns deterministic unit vectors generated by hashing each
/// input text through a lightweight LCG seeded from the text's FNV-1a hash.
use std::path::Path;

use anyhow::{Context, Result};
use sha2::{Digest, Sha256};
use tract_onnx::prelude::*;

// ---------------------------------------------------------------------------
// Type alias for the compiled runnable model.
//
// The chain is:
//   tract_onnx::onnx().model_for_path(...)  → InferenceModel
//   .into_optimized()?                      → TypedModel
//   .into_runnable()?                       → TypedSimplePlan<TypedModel>
//
// TypedModel   = Graph<TypedFact, Box<dyn TypedOp>>
// TypedSimplePlan<M> = SimplePlan<TypedFact, Box<dyn TypedOp>, M>
// ---------------------------------------------------------------------------
type TractModel = TypedSimplePlan<TypedModel>;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// The embedding engine.
pub struct Embedder {
    inner: Box<EmbedderInner>,
}

// ---------------------------------------------------------------------------
// Private inner representation
// ---------------------------------------------------------------------------

enum EmbedderInner {
    /// Real tract-onnx ONNX model.
    Tract {
        model: Box<TractModel>,
        tokenizer: Box<tokenizers::Tokenizer>,
        max_tokens: usize,
        dim: usize,
        /// Whether the model accepts `token_type_ids` (probed during load, then cached).
        has_token_type_ids: bool,
        /// Whether the first output is named `sentence_embedding` (pre-pooled).
        /// If false we mean-pool `last_hidden_state` ourselves.
        is_pre_pooled: bool,
    },

    /// HTTP embedding backend (Ollama / OpenAI-compatible).
    Http {
        url: String,
        model: String,
        dim: usize,
    },

    /// Stub: deterministic random unit vectors derived from text hashes.
    Stub { dim: usize },
}

// ---------------------------------------------------------------------------
// impl Embedder
// ---------------------------------------------------------------------------

impl Embedder {
    /// Load an embedding model from `model_path`.
    ///
    /// `model_path` must point to the `.onnx` file.  The tokenizer is expected
    /// at `{model_path_dir}/tokenizer.json`.
    pub fn load(model_path: &Path, max_tokens: usize) -> Result<Self> {
        let model_dir = model_path
            .parent()
            .with_context(|| format!("model_path has no parent: {}", model_path.display()))?;

        // --- Tokenizer ---
        let tokenizer_path = model_dir.join("tokenizer.json");
        let mut tokenizer = tokenizers::Tokenizer::from_file(&tokenizer_path).map_err(|e| {
            anyhow::anyhow!(
                "failed to load tokenizer from {}: {}",
                tokenizer_path.display(),
                e
            )
        })?;

        // Configure truncation so all sequences are capped at max_tokens.
        tokenizer
            .with_truncation(Some(tokenizers::TruncationParams {
                max_length: max_tokens,
                strategy: tokenizers::TruncationStrategy::LongestFirst,
                stride: 0,
                direction: tokenizers::TruncationDirection::Right,
            }))
            .map_err(|e| anyhow::anyhow!("failed to set truncation: {}", e))?;

        // --- Load the ONNX graph (InferenceModel → optimized TypedModel → runnable plan) ---
        //
        // Some models (e.g. gte-multilingual-base) embed symbolic shape expressions like
        // `Min(65536, sequence_length)` in their input dim_params.  tract's TDim parser can
        // only handle simple names and arithmetic — not function calls — so loading fails.
        //
        // Fix: read the raw ONNX bytes, decode the protobuf, clear all dim_params from inputs
        // (replacing with concrete dim_value = max_tokens for seq dim, 1 for batch), re-encode,
        // and feed to tract via model_for_read.  This is safe: we supply our own input facts
        // anyway, so the proto annotations are informational only.
        use prost::Message as _;
        use tract_onnx::prelude::*;

        let raw = std::fs::read(model_path)
            .with_context(|| format!("reading ONNX file {}", model_path.display()))?;

        let mut proto = tract_onnx::pb::ModelProto::decode(raw.as_slice())
            .with_context(|| format!("decoding ONNX protobuf from {}", model_path.display()))?;

        // Clear symbolic dim_params on every graph input; supply concrete values instead.
        // ONNX shape: dim_value = 0 means dynamic; we set batch=1, seq=max_tokens.
        //
        // Also clear graph.value_info entirely: intermediate tensors may contain
        // symbolic expressions like `Min(65536, sequence_length)` that tract's TDim
        // parser cannot handle (it only supports simple names and arithmetic).
        // Removing value_info is safe — tract infers all intermediate shapes from
        // the input facts we supply below.
        if let Some(graph) = proto.graph.as_mut() {
            for input in graph.input.iter_mut() {
                if let Some(type_proto) = input.r#type.as_mut() {
                    if let Some(tract_onnx::pb::type_proto::Value::TensorType(ref mut tt)) =
                        type_proto.value
                    {
                        if let Some(shape) = tt.shape.as_mut() {
                            for (i, dim) in shape.dim.iter_mut().enumerate() {
                                use tract_onnx::pb::tensor_shape_proto::dimension::Value;
                                // Replace any symbolic expression tract can't parse with concrete.
                                if matches!(dim.value, Some(Value::DimParam(_))) {
                                    dim.value = Some(Value::DimValue(if i == 0 {
                                        1
                                    } else {
                                        max_tokens as i64
                                    }));
                                }
                            }
                        }
                    }
                }
            }

            // Strip intermediate shape annotations that may contain unparseable
            // symbolic expressions (e.g. `Min(65536, sequence_length)` in rotary
            // embedding nodes).  tract derives these shapes from input facts.
            graph.value_info.clear();
        }

        let patched = proto.encode_to_vec();
        let mut inference_model = tract_onnx::onnx()
            .model_for_read(&mut patched.as_slice())
            .with_context(|| format!("loading ONNX model from {}", model_path.display()))?;

        // Detect how many inputs the model expects so we know whether it accepts token_type_ids.
        let input_count = inference_model
            .input_outlets()
            .context("reading model input outlets")?
            .len();
        let has_token_type_ids = input_count >= 3;

        // Supply input facts: dynamic batch (any size), fixed seq_len = max_tokens.
        // Using a symbolic batch dimension lets us embed N texts in one forward pass
        // while still giving tract enough shape information to optimize the graph.
        let fact = InferenceFact::dt_shape(i64::datum_type(), tvec!(1usize, max_tokens));
        for i in 0..input_count {
            inference_model
                .set_input_fact(i, fact.clone())
                .with_context(|| format!("setting input fact for input {i}"))?;
        }

        let typed_model = inference_model
            .into_optimized()
            .context("optimizing ONNX model")?;

        // Detect output name before compiling to a plan.
        // The runnable plan exposes the same outlet_labels as the typed model.
        // We look for a `sentence_embedding` output outlet label.
        let output_outlets = typed_model
            .output_outlets()
            .context("reading model output outlets")?
            .to_vec(); // clone so we don't hold a borrow
        let is_pre_pooled = output_outlets
            .iter()
            .any(|&o| typed_model.outlet_label(o) == Some("sentence_embedding"));

        let model = typed_model
            .into_runnable()
            .context("compiling ONNX model to runnable plan")?;

        // Probe the actual output dimension with a single forward pass (batch=1, seq=max_tokens).
        let dim = probe_dim(
            &model,
            has_token_type_ids,
            is_pre_pooled,
            max_tokens,
            &tokenizer,
        )
        .context("probing embedding dimension")?;

        Ok(Self {
            inner: Box::new(EmbedderInner::Tract {
                model: Box::new(model),
                tokenizer: Box::new(tokenizer),
                max_tokens,
                dim,
                has_token_type_ids,
                is_pre_pooled,
            }),
        })
    }

    /// Create a stub embedder that returns deterministic random unit vectors.
    pub fn stub(dim: usize) -> Self {
        Self {
            inner: Box::new(EmbedderInner::Stub { dim }),
        }
    }

    /// Create an HTTP embedder that calls an Ollama-compatible API.
    ///
    /// Probes the endpoint once to determine the embedding dimension.
    pub fn http(url: &str, model: &str) -> Result<Self> {
        // Probe dimension with a test request.
        let probe = http_embed_request(url, model, &["hello"])?;
        let dim = probe.first()
            .ok_or_else(|| anyhow::anyhow!("HTTP embed probe returned empty result"))?
            .len();

        Ok(Self {
            inner: Box::new(EmbedderInner::Http {
                url: url.to_string(),
                model: model.to_string(),
                dim,
            }),
        })
    }

    /// Return the model name for metadata (used by store to detect model changes).
    pub fn model_name(&self) -> &str {
        match self.inner.as_ref() {
            EmbedderInner::Tract { .. } => "tract-onnx",
            EmbedderInner::Http { model, .. } => model,
            EmbedderInner::Stub { .. } => "stub",
        }
    }

    /// Embed a batch of texts and return one unit-normalised vector per text.
    ///
    /// The returned `Vec` has the same length as `texts`; each inner `Vec<f32>`
    /// has length equal to the model's embedding dimension.
    pub fn embed_batch(&self, texts: &[&str]) -> Result<Vec<Vec<f32>>> {
        embed_batch_inner(&self.inner, texts)
    }

    /// Convenience wrapper: embed a single text.
    pub fn embed_one(&self, text: &str) -> Result<Vec<f32>> {
        let mut batch = self.embed_batch(&[text])?;
        batch
            .pop()
            .ok_or_else(|| anyhow::anyhow!("embed_batch returned empty result"))
    }

    /// Return the lowercase hex sha256 of the model file at `model_path`.
    ///
    /// Stored in `meta.model_sha256` so vec can detect when the model file
    /// has been replaced and prompt the user to run `vec updatedb --full`.
    #[allow(dead_code)]
    pub fn model_sha256(model_path: &Path) -> Result<String> {
        let bytes = std::fs::read(model_path)
            .with_context(|| format!("reading model file: {}", model_path.display()))?;
        let digest = Sha256::digest(&bytes);
        Ok(hex::encode(digest))
    }
}

// ---------------------------------------------------------------------------
// Dimension probe: run a tiny forward pass to learn the output dimension.
// ---------------------------------------------------------------------------

/// Run a minimal forward pass to discover the embedding dimension.
///
/// `seq` must match the sequence length the model was compiled for — the model
/// plan is fixed-shape, so feeding a different length causes a shape clash.
fn probe_dim(
    model: &TractModel,
    has_token_type_ids: bool,
    is_pre_pooled: bool,
    seq: usize,
    tokenizer: &tokenizers::Tokenizer,
) -> Result<usize> {
    let batch = 1usize;
    // Tokenize a real short string so the probe uses IDs from the model's
    // actual vocabulary — not hardcoded BERT CLS/SEP IDs (101/102), which are
    // wrong for non-BERT-family models such as XLMRoberta-based
    // gte-multilingual-base.
    let enc = tokenizer
        .encode("hello", true)
        .map_err(|e| anyhow::anyhow!("probe tokenization failed: {}", e))?;
    let raw_ids = enc.get_ids();
    let ids: Vec<i64> = (0..seq)
        .map(|i| raw_ids.get(i).copied().unwrap_or(0) as i64)
        .collect();
    let mask: Vec<i64> = (0..seq)
        .map(|i| if i < raw_ids.len() { 1 } else { 0 })
        .collect();
    let types: Vec<i64> = vec![0; seq];

    let outputs = run_tract(model, has_token_type_ids, batch, seq, &ids, &mask, &types)?;

    // TValue implements Deref<Target=Tensor>; &* dereferences through that impl.
    let out0: &Tensor = &outputs[0];
    let shape = out0.shape();
    // sentence_embedding: [batch, dim]
    // last_hidden_state:   [batch, seq_len, dim]
    let dim = if is_pre_pooled {
        *shape
            .get(1)
            .ok_or_else(|| anyhow::anyhow!("unexpected sentence_embedding shape: {shape:?}"))?
    } else {
        *shape
            .get(2)
            .ok_or_else(|| anyhow::anyhow!("unexpected last_hidden_state shape: {shape:?}"))?
    };
    Ok(dim)
}

// ---------------------------------------------------------------------------
// Core inference (standalone to avoid self-borrow conflicts)
// ---------------------------------------------------------------------------

fn embed_batch_inner(inner: &EmbedderInner, texts: &[&str]) -> Result<Vec<Vec<f32>>> {
    match inner {
        EmbedderInner::Stub { dim } => {
            let d = *dim;
            Ok(texts.iter().map(|t| stub_embed(t, d)).collect())
        }
        EmbedderInner::Tract {
            model,
            tokenizer,
            dim,
            max_tokens,
            has_token_type_ids,
            is_pre_pooled,
        } => {
            if texts.is_empty() {
                return Ok(vec![]);
            }

            let seq = *max_tokens;
            let d = *dim;
            let htti = *has_token_type_ids;
            let pre_pooled = *is_pre_pooled;

            // Embed texts in parallel — TractModel::run(&self) and
            // Tokenizer::encode(&self) are both Send + Sync.
            use rayon::prelude::*;

            let results: Vec<Result<Vec<f32>>> = texts
                .par_iter()
                .map(|&text| {
                    let enc = tokenizer
                        .encode(text, true)
                        .map_err(|e| anyhow::anyhow!("tokenization failed: {}", e))?;

                    let raw_ids = enc.get_ids();
                    if raw_ids.is_empty() {
                        return Ok(vec![0f32; d]);
                    }

                    let ids: Vec<i64> = (0..seq)
                        .map(|i| raw_ids.get(i).copied().unwrap_or(0) as i64)
                        .collect();
                    let mask: Vec<i64> = (0..seq)
                        .map(|i| if i < raw_ids.len() { 1 } else { 0 })
                        .collect();
                    let types: Vec<i64> = vec![0i64; seq];

                    let outputs = run_tract(model, htti, 1, seq, &ids, &mask, &types)?;
                    let emb = extract_embeddings(&outputs, d, pre_pooled, &mask, 1, seq)?;
                    Ok(emb.into_iter().next().unwrap_or_else(|| vec![0f32; d]))
                })
                .collect();

            // Propagate the first error, if any.
            results.into_iter().collect()
        }
        EmbedderInner::Http { url, model, dim } => {
            if texts.is_empty() {
                return Ok(vec![]);
            }
            // Send in small batches to avoid overwhelming the HTTP endpoint.
            // The caller may pass hundreds of texts (scaled by thread count).
            const HTTP_BATCH: usize = 32;
            let mut embeddings = Vec::with_capacity(texts.len());
            for chunk in texts.chunks(HTTP_BATCH) {
                let mut batch = http_embed_request(url, model, chunk)?;
                embeddings.append(&mut batch);
            }
            // Normalise all vectors to unit length (Ollama doesn't always do this).
            for v in &mut embeddings {
                normalise(v);
                // Verify dimension matches what we probed.
                if v.len() != *dim {
                    anyhow::bail!(
                        "HTTP embedding dimension mismatch: expected {}, got {}",
                        dim,
                        v.len()
                    );
                }
            }
            Ok(embeddings)
        }
    }
}

// ---------------------------------------------------------------------------
// HTTP embedding (Ollama / OpenAI-compatible)
// ---------------------------------------------------------------------------

/// Call an Ollama-compatible `/api/embed` endpoint.
///
/// Sends a batch of texts and returns one embedding vector per text.
fn http_embed_request(url: &str, model: &str, texts: &[&str]) -> Result<Vec<Vec<f32>>> {
    use std::io::{Read, Write};
    use std::net::TcpStream;

    // Parse URL to extract host:port and path.
    let url_str = if url.ends_with('/') { &url[..url.len() - 1] } else { url };
    let without_scheme = url_str
        .strip_prefix("http://")
        .ok_or_else(|| anyhow::anyhow!("embed URL must start with http://: {url}"))?;
    let (host_port, _) = without_scheme.split_once('/').unwrap_or((without_scheme, ""));
    let api_path = "/api/embed";

    // Tell Ollama to truncate inputs that exceed the model's context window.
    // Also cap on our side at ~1500 chars as a safety net — some model variants
    // ignore the truncate flag.
    const MAX_CHARS: usize = 1500;
    let truncated: Vec<String> = texts
        .iter()
        .map(|t| t.chars().take(MAX_CHARS).collect())
        .collect();
    let input: Vec<&str> = truncated.iter().map(|s| s.as_str()).collect();
    let body = serde_json::json!({
        "model": model,
        "input": input,
        "truncate": true,
    })
    .to_string();

    // Raw HTTP POST (no external HTTP crate dependency).
    let mut stream = TcpStream::connect(host_port)
        .with_context(|| format!("connecting to embed endpoint {host_port}"))?;
    stream
        .set_read_timeout(Some(std::time::Duration::from_secs(300)))
        .ok();

    let request = format!(
        "POST {api_path} HTTP/1.1\r\n\
         Host: {host_port}\r\n\
         Content-Type: application/json\r\n\
         Content-Length: {}\r\n\
         Connection: close\r\n\
         \r\n\
         {body}",
        body.len()
    );
    stream.write_all(request.as_bytes())?;

    // Read response.
    let mut response = String::new();
    stream.read_to_string(&mut response)?;

    // Split headers from body.
    let header_end = response
        .find("\r\n\r\n")
        .map(|i| (i, i + 4))
        .or_else(|| response.find("\n\n").map(|i| (i, i + 2)))
        .ok_or_else(|| anyhow::anyhow!("malformed HTTP response from embed endpoint"))?;
    let headers = &response[..header_end.0];
    let raw_body = &response[header_end.1..];

    // Handle chunked transfer encoding: strip chunk-size lines.
    let json_body = if headers.to_lowercase().contains("transfer-encoding: chunked") {
        decode_chunked(raw_body)
    } else {
        raw_body.to_string()
    };

    // Parse Ollama response: {"embeddings": [[f32, ...], ...]}
    let parsed: serde_json::Value = serde_json::from_str(&json_body)
        .with_context(|| format!("parsing embed response JSON (body length: {} bytes)", json_body.len()))?;

    let embeddings = parsed
        .get("embeddings")
        .and_then(|v| v.as_array())
        .ok_or_else(|| {
            // Include the response in the error for debugging.
            let preview = if json_body.len() > 200 { &json_body[..200] } else { &json_body };
            anyhow::anyhow!("embed response missing 'embeddings' array. Response: {preview}")
        })?;

    let mut result = Vec::with_capacity(embeddings.len());
    for emb in embeddings {
        let vec: Vec<f32> = emb
            .as_array()
            .ok_or_else(|| anyhow::anyhow!("embedding is not an array"))?
            .iter()
            .map(|v| v.as_f64().unwrap_or(0.0) as f32)
            .collect();
        result.push(vec);
    }

    Ok(result)
}

/// Decode an HTTP chunked transfer-encoded body.
///
/// Format: each chunk is `<hex-length>\r\n<data>\r\n`, terminated by `0\r\n\r\n`.
fn decode_chunked(raw: &str) -> String {
    let mut result = String::new();
    let mut remaining = raw;
    loop {
        // Skip leading whitespace/newlines.
        remaining = remaining.trim_start();
        if remaining.is_empty() {
            break;
        }
        // Read the hex chunk size.
        let size_end = remaining.find('\r').or_else(|| remaining.find('\n')).unwrap_or(remaining.len());
        let size_str = remaining[..size_end].trim();
        let size = usize::from_str_radix(size_str, 16).unwrap_or(0);
        if size == 0 {
            break;
        }
        // Skip past the size line.
        remaining = &remaining[size_end..];
        if remaining.starts_with("\r\n") {
            remaining = &remaining[2..];
        } else if remaining.starts_with('\n') {
            remaining = &remaining[1..];
        }
        // Take `size` bytes of data.
        let chunk_end = size.min(remaining.len());
        result.push_str(&remaining[..chunk_end]);
        remaining = &remaining[chunk_end..];
    }
    result
}

/// Build tract tensors and run the model, returning the raw TVec<TValue> outputs.
///
/// Rust note: `tract_onnx::tract_ndarray` re-exports ndarray under tract's own
/// version pin.  We use `Array2::from_shape_vec` to build a 2-D i64 array,
/// then call `.into()` which triggers the `From<Array<T,D>> for Tensor` impl
/// provided by tract-data.  `TValue::from(tensor)` wraps it in a `Var` variant
/// (heap-owned, non-shared tensor).
fn run_tract(
    model: &TractModel,
    has_token_type_ids: bool,
    batch: usize,
    seq_len: usize,
    ids_flat: &[i64],
    mask_flat: &[i64],
    type_flat: &[i64],
) -> Result<TVec<TValue>> {
    use tract_onnx::prelude::tract_ndarray::Array2;

    // Build [batch, seq_len] i64 arrays using tract's re-exported ndarray.
    let input_ids: Tensor = Array2::<i64>::from_shape_vec((batch, seq_len), ids_flat.to_vec())
        .context("building input_ids array")?
        .into();

    let attention_mask: Tensor =
        Array2::<i64>::from_shape_vec((batch, seq_len), mask_flat.to_vec())
            .context("building attention_mask array")?
            .into();

    if has_token_type_ids {
        let token_type_ids: Tensor =
            Array2::<i64>::from_shape_vec((batch, seq_len), type_flat.to_vec())
                .context("building token_type_ids array")?
                .into();

        model
            .run(tvec![
                input_ids.into(),
                attention_mask.into(),
                token_type_ids.into(),
            ])
            .context("tract inference (3-input)")
    } else {
        model
            .run(tvec![input_ids.into(), attention_mask.into(),])
            .context("tract inference (2-input)")
    }
}

/// Extract embeddings from tract outputs, update `dim`, and L2-normalise.
///
/// Handles two output formats:
/// - `sentence_embedding` [batch, dim]         — already pooled
/// - `last_hidden_state`  [batch, seq_len, dim] — mean-pooled with attention mask
///
/// `is_pre_pooled` is detected once during `load()` and cached.
fn extract_embeddings(
    outputs: &TVec<TValue>,
    dim: usize,
    is_pre_pooled: bool,
    mask_flat: &[i64],
    batch_size: usize,
    seq_len: usize,
) -> Result<Vec<Vec<f32>>> {
    // `outputs[0]` is a TValue; deref gives us &Tensor (via Deref impl).
    let out0: &Tensor = &outputs[0];

    if is_pre_pooled {
        // Shape: [batch, emb_dim]
        let shape = out0.shape();
        let emb_dim = shape.get(1).copied().unwrap_or(dim);
        // as_slice::<f32>() returns TractResult<&[f32]> (type-checked access to raw bytes)
        let data = out0
            .as_slice::<f32>()
            .context("extracting sentence_embedding f32 data")?;
        Ok(data
            .chunks(emb_dim)
            .map(|row| {
                let mut v = row.to_vec();
                normalise(&mut v);
                v
            })
            .collect())
    } else {
        // Shape: [batch, seq_len, emb_dim]
        let shape = out0.shape();
        let b = shape.first().copied().unwrap_or(batch_size);
        let s = shape.get(1).copied().unwrap_or(seq_len);
        let emb_dim = shape.get(2).copied().unwrap_or(dim);

        let data = out0
            .as_slice::<f32>()
            .context("extracting last_hidden_state f32 data")?;

        let mut result = Vec::with_capacity(b);
        for bi in 0..b {
            let mut pooled = vec![0f32; emb_dim];
            let mut total_mask: f32 = 0.0;
            for si in 0..s {
                let mask_val = mask_flat[bi * seq_len + si] as f32;
                total_mask += mask_val;
                for di in 0..emb_dim {
                    pooled[di] += data[bi * s * emb_dim + si * emb_dim + di] * mask_val;
                }
            }
            if total_mask > 0.0 {
                for x in &mut pooled {
                    *x /= total_mask;
                }
            }
            normalise(&mut pooled);
            result.push(pooled);
        }
        Ok(result)
    }
}

// ---------------------------------------------------------------------------
// Stub embedding: deterministic unit vector from text
// ---------------------------------------------------------------------------

/// Generate a deterministic unit vector of `dim` f32s from `text`.
///
/// Algorithm:
/// 1. Compute a 64-bit FNV-1a hash of the text bytes.  This is the LCG seed.
/// 2. Run an LCG (Knuth's multiplicative constants) to fill `dim` values in [-1.0, 1.0].
/// 3. L2-normalise the result.
fn stub_embed(text: &str, dim: usize) -> Vec<f32> {
    // FNV-1a seed
    let mut hash: u64 = 14_695_981_039_346_656_037;
    for byte in text.as_bytes() {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(1_099_511_628_211);
    }

    const A: u64 = 6_364_136_223_846_793_005;
    const C: u64 = 1_442_695_040_888_963_407;

    let mut state = hash;
    let mut v: Vec<f32> = Vec::with_capacity(dim);
    for _ in 0..dim {
        state = state.wrapping_mul(A).wrapping_add(C);
        let bits = (state >> 32) as u32;
        let f = (bits as f32 / 2_147_483_648.0) - 1.0;
        v.push(f);
    }

    normalise(&mut v);
    v
}

/// In-place L2 normalisation.  No-op if the norm is near zero.
fn normalise(v: &mut [f32]) {
    let norm: f32 = v.iter().map(|x| x * x).sum::<f32>().sqrt();
    if norm > 1e-9 {
        for x in v.iter_mut() {
            *x /= norm;
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn dot(a: &[f32], b: &[f32]) -> f32 {
        a.iter().zip(b.iter()).map(|(x, y)| x * y).sum()
    }

    #[test]
    fn stub_is_unit_length() {
        let mut emb = Embedder::stub(768);
        let v = emb.embed_one("hello world").unwrap();
        assert_eq!(v.len(), 768);
        let norm: f32 = v.iter().map(|x| x * x).sum::<f32>().sqrt();
        assert!((norm - 1.0).abs() < 1e-5, "norm={norm}");
    }

    #[test]
    fn stub_is_deterministic() {
        let mut emb = Embedder::stub(768);
        let a = emb.embed_one("determinism test").unwrap();
        let b = emb.embed_one("determinism test").unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn stub_different_texts_differ() {
        let mut emb = Embedder::stub(768);
        let a = emb.embed_one("foo bar baz").unwrap();
        let b = emb.embed_one("completely different text").unwrap();
        let sim = dot(&a, &b);
        assert!(sim < 0.99, "suspiciously similar stub vectors: sim={sim}");
    }

    #[test]
    fn stub_batch_matches_individual() {
        let mut emb = Embedder::stub(128);
        let texts = vec!["alpha", "beta", "gamma"];
        let batch = emb.embed_batch(&texts).unwrap();
        for (i, text) in texts.iter().enumerate() {
            let single = emb.embed_one(text).unwrap();
            assert_eq!(batch[i], single, "mismatch at index {i}");
        }
    }

    #[test]
    fn model_sha256_produces_hex_string() {
        use std::io::Write;
        let mut tmp = tempfile::NamedTempFile::new().unwrap();
        tmp.write_all(b"fake model bytes").unwrap();
        let digest = Embedder::model_sha256(tmp.path()).unwrap();
        assert_eq!(digest.len(), 64, "sha256 hex must be 64 chars");
        assert!(digest.chars().all(|c| c.is_ascii_hexdigit()));
    }

    // --- New tests ---

    #[test]
    fn load_missing_model_returns_error() {
        let result = Embedder::load(
            std::path::Path::new("/nonexistent/model/path/model.onnx"),
            512,
        );
        assert!(result.is_err(), "loading a non-existent model should fail");
    }

    #[test]
    fn load_missing_tokenizer_returns_error() {
        // Create a temp dir (simulates a model dir) but do NOT put a tokenizer.json there.
        // We point at a fake .onnx file path inside that dir.
        let dir = tempfile::TempDir::new().unwrap();
        let fake_onnx = dir.path().join("model.onnx");
        // The file does not need to exist for the tokenizer check to fire first.
        // (Embedder::load looks for tokenizer.json before loading the ONNX.)
        let result = Embedder::load(&fake_onnx, 512);
        assert!(
            result.is_err(),
            "loading without tokenizer.json should fail"
        );
    }

    #[test]
    fn stub_batch_size_1() {
        let mut emb = Embedder::stub(768);
        let result = emb.embed_batch(&["single text"]).unwrap();
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].len(), 768);
    }

    #[test]
    fn stub_empty_batch() {
        let mut emb = Embedder::stub(768);
        let result = emb.embed_batch(&[]).unwrap();
        assert!(result.is_empty(), "empty batch should return empty Vec");
    }

    #[test]
    fn stub_long_text() {
        // Very long text (10 000 chars) must not panic and must return a valid unit vector.
        let long_text: String = "a".repeat(10_000);
        let mut emb = Embedder::stub(768);
        let result = emb.embed_one(&long_text);
        assert!(result.is_ok(), "long text should not cause an error");
        let vec = result.unwrap();
        assert_eq!(vec.len(), 768);
        let norm: f32 = vec.iter().map(|x| x * x).sum::<f32>().sqrt();
        assert!(
            (norm - 1.0).abs() < 1e-4,
            "result should be a unit vector, norm={norm}"
        );
    }
}
